wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.2
    cli_version: 0.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682096181.184318
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.9.2
      5: 0.15.0
      8:
      - 5
problem:
  desc: null
  value: ResNet
method:
  desc: null
  value: Recurrent
batchsize:
  desc: null
  value: '10'
